### ISSUE TITLE
Plugin Installation Fails with Gradle Build

### ISSUE THREAD

**Issue by pupupu93** [EddyVerbruggen/cordova-plugin-googleplus#65] opened 2015-05-26 11:16 UTC
I just tried to install the plugin as described in the documentation.
Using: "cordova plugin add n1.x-services.plugins.googleplus" I get a 404 error.

Then tried "cordova plugin add https://github.com/EddyVerbruggen/cordova-plug
in-googleplus.git" and got this:

Fetching plugin "https://github.com/EddyVerbruggen/cordova-plugin-googleplus.git
" via git clone
Installing "nl.x-services.plugins.googleplus" for android
Failed to install 'nl.x-services.plugins.googleplus':Error: Unsupported system library (does not work with gradle): com.google.android.gms:play-services-plus
    at C:\myMobileApp\platforms\android\cordova\lib\build.js:280:31
    at Array.forEach (native)
    at Object.builders.gradle.prepBuildFiles (C:\myMobileApp\platforms\android\cordova\lib\build.js:266:38)
    at Object.module.exports.prepBuildFiles (C:\myMobileApp\platforms\android\cordova\lib\build.js:554:20)
    at C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:567:29
    at _fulfilled (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
    at flush (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
Error: Unsupported system library (does not work with gradle): com.google.android.gms:play-services-plus
    at C:\myMobileApp\platforms\android\cordova\lib\build.js:280:31
    at Array.forEach (native)
    at Object.builders.gradle.prepBuildFiles (C:\myMobileApp\platforms\android\cordova\lib\build.js:266:38)
    at Object.module.exports.prepBuildFiles (C:\myMobileApp\platforms\android\cordova\lib\build.js:554:20)
    at C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:567:29
    at _fulfilled (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
    at flush (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)

**Comment by EddyVerbruggen** [comment] 2015-05-26 11:20
Dupe of #64, also see #63.

Use a release version please.

**Closed by EddyVerbruggen** 2015-05-26 11:21 UTC
