### ISSUE TITLE
ios build fails in 5.2.0 and Xcode 9.2

### ISSUE THREAD

**Issue by deliverymanager** [EddyVerbruggen/cordova-plugin-googleplus#458] opened 2018-01-08 17:52 UTC
**fatal error: 'GoogleSignIn/GoogleSignIn.h' file not found**

    Node              : v6.11.4
    npm               : 3.10.10 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

It works in 5.1.1 version of the plugin.

**Comment by lrwhiddon** [comment] 2018-01-08 18:19
I am getting the same.

**Comment by tech-eng** [comment] 2018-01-08 21:37
having same error

**Comment by tech-eng** [comment] 2018-01-08 22:10
Please help!!!

**Comment by itanhduy** [comment] 2018-01-09 03:20
Having same issue. Anyone has fixed this issue?
Duplicate of #459

**Comment by EddyVerbruggen** [comment] 2018-01-09 08:34
Introduced with #420, reverted in 5.2.1.

**Closed by EddyVerbruggen** 2018-01-09 08:34 UTC

**Comment by rcnicke** [comment] 2018-01-09 09:02
Thanks for the fix, I was ripping my hair out over this!

**Comment by EddyVerbruggen** [comment] 2018-01-09 09:10
I hope you have some left 💇‍♂️!
