### ISSUE TITLE
Cannot add the plugin to the project due to an error with gradle

### ISSUE THREAD

**Issue by balthier82** [EddyVerbruggen/cordova-plugin-googleplus#83] opened 2015-07-24 15:19 UTC
When I try to add the plugin to the cordova project it throws the following error:    

    cordova plugin add c:\XXXX\cordova-plugin-googleplus-master
    Installing "cordova-plugin-googleplus" for android
    Failed to install 'cordova-plugin-googleplus':Error: Unsupported system library (does not work with gradle): com.google.android.
    gms:play-services-plus
        at C:\XXXXXX\platforms\android\cordova\lib\build.js:280:31
        at Array.forEach (native)
    ...

What can i do to solve the problem?

**Comment by josschne** [comment] 2015-07-28 05:27
Duplicate of #64

**Closed** 2015-08-16 20:44 UTC
